apiVersion: networking.sfc.comnets.com/v1alpha1
kind: ServiceFunctionChain
metadata:
  labels:
    app.kubernetes.io/name: sfc-k8s-operator
    app.kubernetes.io/managed-by: kustomize
    sfc.comnets.io/name: sfc-service-function-chain
  name: servicefunctionchain-sample
spec:
  ingress:
    image: ddocker122/ingress:latest
    ports:
      - containerPort: 5000
    nodeSelector:
    
  functions:
    - servicefunction-sample-1
    - servicefunction-sample-2
  
  ingressInterface: eth0
  egressInterface: eth0
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-service
  namespace: sfc
spec:
  clusterIP: 10.96.10.30
  selector:
    sfc.comnets.io/name: sfc-service-function-chain  # match your pod labels
  ports:
  - port: 5000
    targetPort: 8080
    nodePort: 30996
  type: NodePort  # or LoadBalancer if you're using a cloud provider
