apiVersion: networking.sfc.comnets.com/v1alpha1
kind: ServiceFunctionChain
metadata:
  labels:
    app.kubernetes.io/name: sfc-k8s-operator
    app.kubernetes.io/managed-by: kustomize
    sfc.comnets.io/name: sfc-service-function-chain
  name: servicefunctionchain-sample
spec:
  forwarder:
    image: ddocker122/cat_breed:latest
    ports:
      - containerPort: 80
    nodeSelector:
    
  functions:
    - servicefunction-sample-1
    - servicefunction-sample-2
  ingressInterface: eth0
  egressInterface: eth0
  
