# This rule is not used by the project sfc-k8s-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to networking.sfc.comnets.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sfc-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: servicefunctionchain-viewer-role
rules:
- apiGroups:
  - networking.sfc.comnets.com
  resources:
  - servicefunctionchains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.sfc.comnets.com
  resources:
  - servicefunctionchains/status
  verbs:
  - get
