apiVersion: networking.sfc.comnets.com/v1alpha1
kind: ServiceFunction
metadata:
  labels:
    app.kubernetes.io/name: sfc-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: servicefunction-sample
spec:
  image: myregistry.io/firewall:latest
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
  ports:
    - containerPort: 80
  nodeSelector:
    # sfc-role: node-a
  
