apiVersion: v1
kind: Pod
metadata:
  name: destination-app
  namespace: sfc
  labels:
    app: destination-app
spec:
  containers:
    - name: destination-app
      image: ddocker122/app:latest
      ports:
        - containerPort: 5000
