apiVersion: networking.sfc.comnets.com/v1alpha1
kind: ServiceFunction
metadata:
  labels:
    app.kubernetes.io/name: sfc-k8s-operator
    app.kubernetes.io/managed-by: kustomize
    sfc.comnets.io/name: sfc-service-function
    sfc.comnets.io/sf: sfc-sf-1
  name: servicefunction-sample-1
spec:
  image: ddocker122/forwarder:latest
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
  ports:
    - containerPort: 5000
  hostsf:
    name: user-defined-sf
    image: ddocker122/sf1:latest
    ports:
      - containerPort: 5000
  nextsf:
    name: servicefunction-sample-2
    ports:
      - containerPort: 5000
  nodeSelector:
    # sfc-role: node-a
---
apiVersion: networking.sfc.comnets.com/v1alpha1
kind: ServiceFunction
metadata:
  labels:
    app.kubernetes.io/name: sfc-k8s-operator
    app.kubernetes.io/managed-by: kustomize
    sfc.comnets.io/name: sfc-service-function
    sfc.comnets.io/sf: sfc-sf-2
  name: servicefunction-sample-2
spec:
  image: ddocker122/forwarder:latest
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
  ports:
    - containerPort: 5000
  hostsf:
    name: user-defined-sf
    image: ddocker122/sf2:latest
    ports:
      - containerPort: 5000
  nextsf:
    name: servicefunction-sample-2
    ports:
      - containerPort: 5000
  nodeSelector:
    # sfc-role: node-b

